version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    
      timeseriesdb:
    ports:
        - 8086:8086
    image: influxdb:1.7.9
    environment:
        INFLUXDB_DB: timeseriesdb
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: password
        
        