version: '3'
services:
  influxdb:
    ports:
      - 8086:8086
    image: influxdb:1.7.9
    environment:
      INFLUXDB_DB: timeseriesdb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb